# Generated by Django 5.2.8 on 2025-11-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('site', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(max_length=100)),
                ('remoto', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('aprendiz', 'Jovem Aprendiz'), ('estagio', 'Estágio')], max_length=20)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.empresa')),
            ],
        ),
    ]
